// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: meshtastic/powermon.proto
// Protobuf C++ Version: 6.31.1

#include "meshtastic/powermon.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace meshtastic {

inline constexpr PowerStressMessage::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        cmd_{static_cast< ::meshtastic::PowerStressMessage_Opcode >(0)},
        num_seconds_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PowerStressMessage::PowerStressMessage(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(PowerStressMessage_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PowerStressMessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PowerStressMessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PowerStressMessageDefaultTypeInternal() {}
  union {
    PowerStressMessage _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PowerStressMessageDefaultTypeInternal _PowerStressMessage_default_instance_;
template <typename>
PROTOBUF_CONSTEXPR PowerMon::PowerMon(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(PowerMon_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct PowerMonDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PowerMonDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PowerMonDefaultTypeInternal() {}
  union {
    PowerMon _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PowerMonDefaultTypeInternal _PowerMon_default_instance_;
}  // namespace meshtastic
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_meshtastic_2fpowermon_2eproto[2];
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_meshtastic_2fpowermon_2eproto = nullptr;
const ::uint32_t
    TableStruct_meshtastic_2fpowermon_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x000, // bitmap
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::meshtastic::PowerStressMessage, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::meshtastic::PowerStressMessage, _impl_.cmd_),
        PROTOBUF_FIELD_OFFSET(::meshtastic::PowerStressMessage, _impl_.num_seconds_),
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::meshtastic::PowerMon)},
        {1, sizeof(::meshtastic::PowerStressMessage)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::meshtastic::_PowerMon_default_instance_._instance,
    &::meshtastic::_PowerStressMessage_default_instance_._instance,
};
const char descriptor_table_protodef_meshtastic_2fpowermon_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\031meshtastic/powermon.proto\022\nmeshtastic\""
    "\340\001\n\010PowerMon\"\323\001\n\005State\022\010\n\004None\020\000\022\021\n\rCPU_"
    "DeepSleep\020\001\022\022\n\016CPU_LightSleep\020\002\022\014\n\010Vext1"
    "_On\020\004\022\r\n\tLora_RXOn\020\010\022\r\n\tLora_TXOn\020\020\022\021\n\rL"
    "ora_RXActive\020 \022\t\n\005BT_On\020@\022\013\n\006LED_On\020\200\001\022\016"
    "\n\tScreen_On\020\200\002\022\023\n\016Screen_Drawing\020\200\004\022\014\n\007W"
    "ifi_On\020\200\010\022\017\n\nGPS_Active\020\200\020\"\377\002\n\022PowerStre"
    "ssMessage\0222\n\003cmd\030\001 \001(\0162%.meshtastic.Powe"
    "rStressMessage.Opcode\022\023\n\013num_seconds\030\002 \001"
    "(\002\"\237\002\n\006Opcode\022\t\n\005UNSET\020\000\022\016\n\nPRINT_INFO\020\001"
    "\022\017\n\013FORCE_QUIET\020\002\022\r\n\tEND_QUIET\020\003\022\r\n\tSCRE"
    "EN_ON\020\020\022\016\n\nSCREEN_OFF\020\021\022\014\n\010CPU_IDLE\020 \022\021\n"
    "\rCPU_DEEPSLEEP\020!\022\016\n\nCPU_FULLON\020\"\022\n\n\006LED_"
    "ON\0200\022\013\n\007LED_OFF\0201\022\014\n\010LORA_OFF\020@\022\013\n\007LORA_"
    "TX\020A\022\013\n\007LORA_RX\020B\022\n\n\006BT_OFF\020P\022\t\n\005BT_ON\020Q"
    "\022\014\n\010WIFI_OFF\020`\022\013\n\007WIFI_ON\020a\022\013\n\007GPS_OFF\020p"
    "\022\n\n\006GPS_ON\020qBc\n\023com.geeksville.meshB\016Pow"
    "erMonProtosZ\"github.com/meshtastic/go/ge"
    "nerated\252\002\024Meshtastic.Protobufs\272\002\000b\006proto"
    "3"
};
static ::absl::once_flag descriptor_table_meshtastic_2fpowermon_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_meshtastic_2fpowermon_2eproto = {
    false,
    false,
    761,
    descriptor_table_protodef_meshtastic_2fpowermon_2eproto,
    "meshtastic/powermon.proto",
    &descriptor_table_meshtastic_2fpowermon_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_meshtastic_2fpowermon_2eproto::offsets,
    file_level_enum_descriptors_meshtastic_2fpowermon_2eproto,
    file_level_service_descriptors_meshtastic_2fpowermon_2eproto,
};
namespace meshtastic {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL PowerMon_State_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_meshtastic_2fpowermon_2eproto);
  return file_level_enum_descriptors_meshtastic_2fpowermon_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t PowerMon_State_internal_data_[] = {
    196608u, 327744u, 536879138u, 536870912u, 1024u, 256u, 2048u, 128u, 512u, };
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL PowerStressMessage_Opcode_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_meshtastic_2fpowermon_2eproto);
  return file_level_enum_descriptors_meshtastic_2fpowermon_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t PowerStressMessage_Opcode_internal_data_[] = {
    262144u, 128u, 1879060480u, 1879060480u, 805318656u, 12288u, };
// ===================================================================

class PowerMon::_Internal {
 public:
};

PowerMon::PowerMon(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, PowerMon_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:meshtastic.PowerMon)
}
PowerMon::PowerMon(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const PowerMon& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, PowerMon_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PowerMon* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:meshtastic.PowerMon)
}

inline void* PROTOBUF_NONNULL PowerMon::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PowerMon(arena);
}
constexpr auto PowerMon::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(PowerMon),
                                            alignof(PowerMon));
}
constexpr auto PowerMon::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_PowerMon_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &PowerMon::MergeImpl,
          ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<PowerMon>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PowerMon::SharedDtor,
          ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<PowerMon>(), &PowerMon::ByteSizeLong,
              &PowerMon::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PowerMon, _impl_._cached_size_),
          false,
      },
      &PowerMon::kDescriptorMethods,
      &descriptor_table_meshtastic_2fpowermon_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PowerMon_class_data_ =
        PowerMon::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PowerMon::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PowerMon_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PowerMon_class_data_.tc_table);
  return PowerMon_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2>
PowerMon::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    PowerMon_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::meshtastic::PowerMon>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, // no field_entries, or aux_entries
  {{
  }},
};







::google::protobuf::Metadata PowerMon::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class PowerStressMessage::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<PowerStressMessage>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PowerStressMessage, _impl_._has_bits_);
};

PowerStressMessage::PowerStressMessage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PowerStressMessage_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:meshtastic.PowerStressMessage)
}
PowerStressMessage::PowerStressMessage(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PowerStressMessage& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PowerStressMessage_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE PowerStressMessage::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void PowerStressMessage::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, cmd_),
           0,
           offsetof(Impl_, num_seconds_) -
               offsetof(Impl_, cmd_) +
               sizeof(Impl_::num_seconds_));
}
PowerStressMessage::~PowerStressMessage() {
  // @@protoc_insertion_point(destructor:meshtastic.PowerStressMessage)
  SharedDtor(*this);
}
inline void PowerStressMessage::SharedDtor(MessageLite& self) {
  PowerStressMessage& this_ = static_cast<PowerStressMessage&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL PowerStressMessage::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PowerStressMessage(arena);
}
constexpr auto PowerStressMessage::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(PowerStressMessage),
                                            alignof(PowerStressMessage));
}
constexpr auto PowerStressMessage::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_PowerStressMessage_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &PowerStressMessage::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PowerStressMessage>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PowerStressMessage::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PowerStressMessage>(), &PowerStressMessage::ByteSizeLong,
              &PowerStressMessage::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PowerStressMessage, _impl_._cached_size_),
          false,
      },
      &PowerStressMessage::kDescriptorMethods,
      &descriptor_table_meshtastic_2fpowermon_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PowerStressMessage_class_data_ =
        PowerStressMessage::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PowerStressMessage::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PowerStressMessage_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PowerStressMessage_class_data_.tc_table);
  return PowerStressMessage_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2>
PowerStressMessage::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PowerStressMessage, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    PowerStressMessage_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::meshtastic::PowerStressMessage>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // float num_seconds = 2;
    {::_pbi::TcParser::FastF32S1,
     {21, 1, 0, PROTOBUF_FIELD_OFFSET(PowerStressMessage, _impl_.num_seconds_)}},
    // .meshtastic.PowerStressMessage.Opcode cmd = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PowerStressMessage, _impl_.cmd_), 0>(),
     {8, 0, 0, PROTOBUF_FIELD_OFFSET(PowerStressMessage, _impl_.cmd_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .meshtastic.PowerStressMessage.Opcode cmd = 1;
    {PROTOBUF_FIELD_OFFSET(PowerStressMessage, _impl_.cmd_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // float num_seconds = 2;
    {PROTOBUF_FIELD_OFFSET(PowerStressMessage, _impl_.num_seconds_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void PowerStressMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:meshtastic.PowerStressMessage)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    ::memset(&_impl_.cmd_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.num_seconds_) -
        reinterpret_cast<char*>(&_impl_.cmd_)) + sizeof(_impl_.num_seconds_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PowerStressMessage::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PowerStressMessage& this_ = static_cast<const PowerStressMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PowerStressMessage::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PowerStressMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:meshtastic.PowerStressMessage)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .meshtastic.PowerStressMessage.Opcode cmd = 1;
  if ((this_._impl_._has_bits_[0] & 0x00000001u) != 0) {
    if (this_._internal_cmd() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          1, this_._internal_cmd(), target);
    }
  }

  // float num_seconds = 2;
  if ((this_._impl_._has_bits_[0] & 0x00000002u) != 0) {
    if (::absl::bit_cast<::uint32_t>(this_._internal_num_seconds()) != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteFloatToArray(
          2, this_._internal_num_seconds(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:meshtastic.PowerStressMessage)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PowerStressMessage::ByteSizeLong(const MessageLite& base) {
  const PowerStressMessage& this_ = static_cast<const PowerStressMessage&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PowerStressMessage::ByteSizeLong() const {
  const PowerStressMessage& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:meshtastic.PowerStressMessage)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    // .meshtastic.PowerStressMessage.Opcode cmd = 1;
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (this_._internal_cmd() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_cmd());
      }
    }
    // float num_seconds = 2;
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (::absl::bit_cast<::uint32_t>(this_._internal_num_seconds()) != 0) {
        total_size += 5;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PowerStressMessage::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PowerStressMessage*>(&to_msg);
  auto& from = static_cast<const PowerStressMessage&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:meshtastic.PowerStressMessage)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      if (from._internal_cmd() != 0) {
        _this->_impl_.cmd_ = from._impl_.cmd_;
      }
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      if (::absl::bit_cast<::uint32_t>(from._internal_num_seconds()) != 0) {
        _this->_impl_.num_seconds_ = from._impl_.num_seconds_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PowerStressMessage::CopyFrom(const PowerStressMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:meshtastic.PowerStressMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PowerStressMessage::InternalSwap(PowerStressMessage* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PowerStressMessage, _impl_.num_seconds_)
      + sizeof(PowerStressMessage::_impl_.num_seconds_)
      - PROTOBUF_FIELD_OFFSET(PowerStressMessage, _impl_.cmd_)>(
          reinterpret_cast<char*>(&_impl_.cmd_),
          reinterpret_cast<char*>(&other->_impl_.cmd_));
}

::google::protobuf::Metadata PowerStressMessage::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace meshtastic
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_meshtastic_2fpowermon_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
