// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: meshtastic/remote_hardware.proto
// Protobuf C++ Version: 6.32.0

#ifndef meshtastic_2fremote_5fhardware_2eproto_2epb_2eh
#define meshtastic_2fremote_5fhardware_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6032000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_meshtastic_2fremote_5fhardware_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_meshtastic_2fremote_5fhardware_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_meshtastic_2fremote_5fhardware_2eproto;
}  // extern "C"
namespace meshtastic {
enum HardwareMessage_Type : int;
extern const uint32_t HardwareMessage_Type_internal_data_[];
class HardwareMessage;
struct HardwareMessageDefaultTypeInternal;
extern HardwareMessageDefaultTypeInternal _HardwareMessage_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull HardwareMessage_class_data_;
}  // namespace meshtastic
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::meshtastic::HardwareMessage_Type_internal_data_>
    internal::EnumTraitsImpl::value<::meshtastic::HardwareMessage_Type>;
}  // namespace protobuf
}  // namespace google

namespace meshtastic {
enum HardwareMessage_Type : int {
  HardwareMessage_Type_UNSET = 0,
  HardwareMessage_Type_WRITE_GPIOS = 1,
  HardwareMessage_Type_WATCH_GPIOS = 2,
  HardwareMessage_Type_GPIOS_CHANGED = 3,
  HardwareMessage_Type_READ_GPIOS = 4,
  HardwareMessage_Type_READ_GPIOS_REPLY = 5,
  HardwareMessage_Type_HardwareMessage_Type_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  HardwareMessage_Type_HardwareMessage_Type_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t HardwareMessage_Type_internal_data_[];
inline constexpr HardwareMessage_Type HardwareMessage_Type_Type_MIN =
    static_cast<HardwareMessage_Type>(0);
inline constexpr HardwareMessage_Type HardwareMessage_Type_Type_MAX =
    static_cast<HardwareMessage_Type>(5);
inline bool HardwareMessage_Type_IsValid(int value) {
  return 0 <= value && value <= 5;
}
inline constexpr int HardwareMessage_Type_Type_ARRAYSIZE = 5 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL HardwareMessage_Type_descriptor();
template <typename T>
const ::std::string& HardwareMessage_Type_Name(T value) {
  static_assert(::std::is_same<T, HardwareMessage_Type>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to Type_Name().");
  return HardwareMessage_Type_Name(static_cast<HardwareMessage_Type>(value));
}
template <>
inline const ::std::string& HardwareMessage_Type_Name(HardwareMessage_Type value) {
  return ::google::protobuf::internal::NameOfDenseEnum<HardwareMessage_Type_descriptor, 0, 5>(
      static_cast<int>(value));
}
inline bool HardwareMessage_Type_Parse(
    ::absl::string_view name, HardwareMessage_Type* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<HardwareMessage_Type>(HardwareMessage_Type_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class HardwareMessage final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:meshtastic.HardwareMessage) */ {
 public:
  inline HardwareMessage() : HardwareMessage(nullptr) {}
  ~HardwareMessage() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(HardwareMessage* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(HardwareMessage));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR HardwareMessage(::google::protobuf::internal::ConstantInitialized);

  inline HardwareMessage(const HardwareMessage& from) : HardwareMessage(nullptr, from) {}
  inline HardwareMessage(HardwareMessage&& from) noexcept
      : HardwareMessage(nullptr, ::std::move(from)) {}
  inline HardwareMessage& operator=(const HardwareMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline HardwareMessage& operator=(HardwareMessage&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HardwareMessage& default_instance() {
    return *reinterpret_cast<const HardwareMessage*>(
        &_HardwareMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(HardwareMessage& a, HardwareMessage& b) { a.Swap(&b); }
  inline void Swap(HardwareMessage* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HardwareMessage* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HardwareMessage* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<HardwareMessage>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const HardwareMessage& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const HardwareMessage& from) { HardwareMessage::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(HardwareMessage* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "meshtastic.HardwareMessage"; }

 protected:
  explicit HardwareMessage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  HardwareMessage(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const HardwareMessage& from);
  HardwareMessage(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, HardwareMessage&& from) noexcept
      : HardwareMessage(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using Type = HardwareMessage_Type;
  static constexpr Type UNSET = HardwareMessage_Type_UNSET;
  static constexpr Type WRITE_GPIOS = HardwareMessage_Type_WRITE_GPIOS;
  static constexpr Type WATCH_GPIOS = HardwareMessage_Type_WATCH_GPIOS;
  static constexpr Type GPIOS_CHANGED = HardwareMessage_Type_GPIOS_CHANGED;
  static constexpr Type READ_GPIOS = HardwareMessage_Type_READ_GPIOS;
  static constexpr Type READ_GPIOS_REPLY = HardwareMessage_Type_READ_GPIOS_REPLY;
  static inline bool Type_IsValid(int value) {
    return HardwareMessage_Type_IsValid(value);
  }
  static constexpr Type Type_MIN = HardwareMessage_Type_Type_MIN;
  static constexpr Type Type_MAX = HardwareMessage_Type_Type_MAX;
  static constexpr int Type_ARRAYSIZE = HardwareMessage_Type_Type_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL Type_descriptor() {
    return HardwareMessage_Type_descriptor();
  }
  template <typename T>
  static inline const ::std::string& Type_Name(T value) {
    return HardwareMessage_Type_Name(value);
  }
  static inline bool Type_Parse(
      ::absl::string_view name, Type* PROTOBUF_NONNULL value) {
    return HardwareMessage_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kGpioMaskFieldNumber = 2,
    kGpioValueFieldNumber = 3,
    kTypeFieldNumber = 1,
  };
  // uint64 gpio_mask = 2;
  void clear_gpio_mask() ;
  ::uint64_t gpio_mask() const;
  void set_gpio_mask(::uint64_t value);

  private:
  ::uint64_t _internal_gpio_mask() const;
  void _internal_set_gpio_mask(::uint64_t value);

  public:
  // uint64 gpio_value = 3;
  void clear_gpio_value() ;
  ::uint64_t gpio_value() const;
  void set_gpio_value(::uint64_t value);

  private:
  ::uint64_t _internal_gpio_value() const;
  void _internal_set_gpio_value(::uint64_t value);

  public:
  // .meshtastic.HardwareMessage.Type type = 1;
  void clear_type() ;
  ::meshtastic::HardwareMessage_Type type() const;
  void set_type(::meshtastic::HardwareMessage_Type value);

  private:
  ::meshtastic::HardwareMessage_Type _internal_type() const;
  void _internal_set_type(::meshtastic::HardwareMessage_Type value);

  public:
  // @@protoc_insertion_point(class_scope:meshtastic.HardwareMessage)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const HardwareMessage& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint64_t gpio_mask_;
    ::uint64_t gpio_value_;
    int type_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_meshtastic_2fremote_5fhardware_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull HardwareMessage_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// HardwareMessage

// .meshtastic.HardwareMessage.Type type = 1;
inline void HardwareMessage::clear_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004U;
}
inline ::meshtastic::HardwareMessage_Type HardwareMessage::type() const {
  // @@protoc_insertion_point(field_get:meshtastic.HardwareMessage.type)
  return _internal_type();
}
inline void HardwareMessage::set_type(::meshtastic::HardwareMessage_Type value) {
  _internal_set_type(value);
  _impl_._has_bits_[0] |= 0x00000004U;
  // @@protoc_insertion_point(field_set:meshtastic.HardwareMessage.type)
}
inline ::meshtastic::HardwareMessage_Type HardwareMessage::_internal_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::meshtastic::HardwareMessage_Type>(_impl_.type_);
}
inline void HardwareMessage::_internal_set_type(::meshtastic::HardwareMessage_Type value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = value;
}

// uint64 gpio_mask = 2;
inline void HardwareMessage::clear_gpio_mask() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gpio_mask_ = ::uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000001U;
}
inline ::uint64_t HardwareMessage::gpio_mask() const {
  // @@protoc_insertion_point(field_get:meshtastic.HardwareMessage.gpio_mask)
  return _internal_gpio_mask();
}
inline void HardwareMessage::set_gpio_mask(::uint64_t value) {
  _internal_set_gpio_mask(value);
  _impl_._has_bits_[0] |= 0x00000001U;
  // @@protoc_insertion_point(field_set:meshtastic.HardwareMessage.gpio_mask)
}
inline ::uint64_t HardwareMessage::_internal_gpio_mask() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.gpio_mask_;
}
inline void HardwareMessage::_internal_set_gpio_mask(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gpio_mask_ = value;
}

// uint64 gpio_value = 3;
inline void HardwareMessage::clear_gpio_value() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gpio_value_ = ::uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000002U;
}
inline ::uint64_t HardwareMessage::gpio_value() const {
  // @@protoc_insertion_point(field_get:meshtastic.HardwareMessage.gpio_value)
  return _internal_gpio_value();
}
inline void HardwareMessage::set_gpio_value(::uint64_t value) {
  _internal_set_gpio_value(value);
  _impl_._has_bits_[0] |= 0x00000002U;
  // @@protoc_insertion_point(field_set:meshtastic.HardwareMessage.gpio_value)
}
inline ::uint64_t HardwareMessage::_internal_gpio_value() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.gpio_value_;
}
inline void HardwareMessage::_internal_set_gpio_value(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gpio_value_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace meshtastic


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::meshtastic::HardwareMessage_Type> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::meshtastic::HardwareMessage_Type>() {
  return ::meshtastic::HardwareMessage_Type_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // meshtastic_2fremote_5fhardware_2eproto_2epb_2eh
